version: '3.2'

services:
  zoo:
    image: confluentinc/cp-zookeeper:5.3.1
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: server.1=zoo:2888:3888
    volumes:
      - ./poc/zoo/data:/data
      -  ./poc/zoo/datalog:/datalog

  kafka:
    image: confluentinc/cp-kafka:5.3.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092"
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=ERROR,kafka.producer.async.DefaultEventHandler=ERROR,state.change.logger=ERROR"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - ./poc/kafka/data:/var/lib/kafka/data
    depends_on:
      - zoo

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    # restart: always
    # network_mode: host
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    # restart: always
    # network_mode: host
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://localhost:9200


# Must be mounted like this or else permission aren't correct
volumes:
  esdata:
    driver: local

